"""
Django settings for olitest project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import olitest.other_settings as other_settings
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e402&9fvf0#23)1iz&kiyhfxuyyk@ut!gy+$4rwcp@a9yd%lux'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['djangotest.127.0.0.1.xip.io', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # delete?
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Plex',
    'playlist'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'olitest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'olitest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django',
        'HOST': 'lroi-databroker-db',
        'USER': 'root',
        'PASSWORD': 'test1234'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_REDIRECT_URL = ''

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# GBSFM settings

# IMPORTANT - SA validation will not happen if this is set to False
IS_LIVE = True

LOGIC_DIR = os.path.join(BASE_DIR, 'playlist', 'logic')
ICES_CONF = os.path.join(LOGIC_DIR, 'ices.conf')
IMAGES_DIR = os.path.join(BASE_DIR, 'playlist', 'images')

SCTRANS_DIR = '/srv/sc_trans'
SCTRANS_CONF = os.path.join(SCTRANS_DIR, 'sc_trans.conf')
SCSERV_DIR = os.path.join(BASE_DIR, 'sc_serv')
SCSERV_CONF = os.path.join(SCSERV_DIR, 'sc_serv.conf')

# The password for the /next endpoint
NEXT_PASSWORD = other_settings.NEXT_PASSWORD

#FTP_BASE_DIR = os.path.join(BASE_DIR, 'ftpdir')
FTP_BASE_DIR = '/srv/ftpdir'
MAX_UPLOAD_SIZE = 115000000
MAX_UPLOAD_SIZE = 536870912
MAX_SONG_LENGTH = 660

# Add SA account details to other_settings.py before going live
SA_USERNAME = other_settings.SA_USERNAME
SA_PASSWORD = other_settings.SA_PASSWORD

# Max number of songs allowed to be queued by a user without tokens
PLAYLIST_MAX = 1

# How long before a song can be played again, in hours
REPLAY_INTERVAL = 24 * 8

#STREAMINFO_URL = "http://gbsfm:8000/statistics"
STREAMINFO_URL = "http://admin:adminpassword@192.168.0.154:8888/admin/stats"
LOG_LEVEL = "DEBUG"
LOG_FILE = os.path.join(BASE_DIR, 'pydj.log')
SHOW_QUERIES = False
LOG_DIR = '/srv/logs'
EMOTICONS_URL = "http://forums.somethingawful.com/misc.php?action=showsmilies"

#forums settings

COMMENTS_ALLOW_PROFANITIES = True

# cache setting

CACHE_BACKEND = os.path.join(BASE_DIR, 'cache')
CACHE_MIDDLEWARE_SECONDS = 1
